version: '3.8'

services:
  backend:
    build: .
    container_name: hrc-backend
    ports:
      - "5011:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000 
      - DB_HOST=database
      - DB_PORT=3311 # 🚨 Tetap 3306 karena komunikasi internal antar-container
      - DB_USER=hrc_user
      - DB_PASSWORD=hrc_secret_password
      - DB_NAME=pendaftaran_hrc
      - FRONTEND_URL=https://pendaftaran-hrc-frontendd.vercel.app/
      - MIDTRANS_SERVER_KEY=Mid-server-KODE
      - MIDTRANS_CLIENT_KEY=Mid-client-KODE 
    depends_on:
      database:
        condition: service_healthy

  database: 
    image: mysql:8.0
    container_name: hrc-database
    ports:
      - "3311:3306" # Port 3307 jika kamu ingin remote database dari aplikasi luar (seperti DBeaver/Navicat)
    environment:
      - MYSQL_ROOT_PASSWORD=super_secret_root_password
      - MYSQL_DATABASE=pendaftaran_hrc
      - MYSQL_USER=hrc_user
      - MYSQL_PASSWORD=hrc_secret_password
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "hrc_user", "-phrc_secret_password"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s

volumes:
  mysql_data: